# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up natuna
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
  docker-pull-ec2:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Creating a SSH CONFIG file
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}

      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/deployment.pem
        chmod 600 ~/.ssh/deployment.pem
        cat >> ~/.ssh/config << END
        Host deploy_ec2
          Hostname $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/deployment.pem
          StrictHostKeyChecking no
        END
    - name: Deploy to EC2
      env:
        PATH_FILE: natuna-app
        PROJECT_NAME: natuna/app

      run: |
        ssh deploy_ec2 "mkdir temp"
        ssh deploy_ec2 "git clone https://github.com/farrelarrizal/natuna-app.git temp"
        ssh deploy_ec2 "rsync -a temp/ $PATH_FILE"
        ssh deploy_ec2 "rm -rf temp"
        ssh deploy_ec2 "cd $PATH_FILE"
        ssh deploy_ec2 "cd $PATH_FILE && sail down"
        ssh deploy_ec2 "cd $PATH_FILE && sail build && sail up -d"
        
      
